from .backend import *


class UiMixin:
    def _setup_style(self) -> None:
        style = ttk.Style(self)
        style.theme_use("clam")
        style.configure("TFrame", background=BG)
        style.configure("Panel.TFrame", background=PANEL)
        style.configure("Card.TFrame", background=PANEL_2)
        style.configure("TLabel", background=BG, foreground=TEXT, font=("Sans", 10))
        style.configure("Panel.TLabel", background=PANEL, foreground=TEXT)
        style.configure("Card.TLabel", background=PANEL_2, foreground=TEXT)
        style.configure("Muted.TLabel", background=BG, foreground=MUTED)
        style.configure("PanelMuted.TLabel", background=PANEL, foreground=MUTED)
        style.configure("Title.TLabel", background=BG, foreground=TEXT, font=("Sans", 20, "bold"))
        style.configure("CardTitle.TLabel", background=PANEL_2, foreground=TEXT, font=("Sans", 14, "bold"))
        style.configure("Accent.TButton", background=PURPLE, foreground="#ffffff", borderwidth=0, padding=(16, 10), font=("Sans", 10, "bold"))
        style.map("Accent.TButton", background=[("active", "#b18cff"), ("disabled", "#4a405d")])
        style.configure("Danger.TButton", background=RED, foreground="#ffffff", borderwidth=0, padding=(14, 9))
        style.map("Danger.TButton", background=[("active", "#ff6b85")])
        style.configure("TButton", background=PANEL_2, foreground=TEXT, borderwidth=1, padding=(12, 8))
        style.map("TButton", background=[("active", "#23232a")])
        style.configure("TEntry", fieldbackground=PANEL_2, foreground=TEXT, insertcolor=TEXT, bordercolor=BORDER, padding=8)
        style.configure("TCombobox", fieldbackground=PANEL_2, background=PANEL_2, foreground=TEXT, arrowcolor=TEXT, padding=7)
        style.map("TCombobox", fieldbackground=[("readonly", PANEL_2)], foreground=[("readonly", TEXT)])
        style.configure("Treeview", background=PANEL, fieldbackground=PANEL, foreground=TEXT, rowheight=34, borderwidth=0)
        style.configure("Treeview.Heading", background=PANEL_2, foreground=MUTED, relief="flat", font=("Sans", 9, "bold"))
        style.map("Treeview", background=[("selected", "#372750")], foreground=[("selected", "#ffffff")])
        style.configure("Horizontal.TProgressbar", troughcolor=PANEL_2, background=PURPLE, borderwidth=0)

    def _build_ui(self) -> None:
        header = ttk.Frame(self, padding=(24, 18, 24, 12))
        header.pack(fill="x")
        ttk.Label(header, text=APP_NAME, style="Title.TLabel").pack(side="left")
        self.account_label = ttk.Label(header, text="Not signed in", style="Muted.TLabel")
        self.account_label.pack(side="right", padx=(10, 0))
        ttk.Button(header, text="Sign out", style="Danger.TButton", command=self.logout).pack(side="right")

        body = ttk.Panedwindow(self, orient="horizontal")
        body.pack(fill="both", expand=True, padx=22, pady=(0, 18))

        left = ttk.Frame(body, style="Panel.TFrame", padding=16)
        right = ttk.Frame(body, style="Panel.TFrame", padding=16)
        body.add(left, weight=3)
        body.add(right, weight=2)

        top = ttk.Frame(left, style="Panel.TFrame")
        top.pack(fill="x", pady=(0, 12))
        self.search_var = tk.StringVar()
        self.search_var.trace_add("write", lambda *_: self._apply_filter())
        ttk.Entry(top, textvariable=self.search_var).pack(side="left", fill="x", expand=True)
        ttk.Button(top, text="Refresh", command=self.refresh_library).pack(side="left", padx=(8, 0))
        ttk.Button(top, text="QR sign-in", style="Accent.TButton", command=self.qr_login).pack(side="left", padx=(8, 0))

        columns = ("name", "appid", "type")
        self.tree = ttk.Treeview(left, columns=columns, show="headings", selectmode="browse")
        self.tree.heading("name", text="Owned game / app")
        self.tree.heading("appid", text="AppID")
        self.tree.heading("type", text="Type")
        self.tree.column("name", width=420, minwidth=220)
        self.tree.column("appid", width=90, anchor="center")
        self.tree.column("type", width=100, anchor="center")
        self.tree.bind("<<TreeviewSelect>>", lambda _e: self._selection_changed())
        scroll = ttk.Scrollbar(left, orient="vertical", command=self.tree.yview)
        self.tree.configure(yscrollcommand=scroll.set)
        self.tree.pack(side="left", fill="both", expand=True)
        scroll.pack(side="right", fill="y")

        self.details_title = ttk.Label(right, text="Select an owned game", style="CardTitle.TLabel")
        self.details_title.pack(fill="x", pady=(0, 4))
        self.details_meta = ttk.Label(right, text="", style="PanelMuted.TLabel")
        self.details_meta.pack(fill="x", pady=(0, 16))

        form = ttk.Frame(right, style="Panel.TFrame")
        form.pack(fill="x")
        self.os_var = tk.StringVar(value=str(self.config_data.get("os", "linux")))
        self.arch_var = tk.StringVar(value=str(self.config_data.get("arch", "64")))
        self.language_var = tk.StringVar(value=str(self.config_data.get("language", "english")))
        self.branch_var = tk.StringVar(value=str(self.config_data.get("branch", "public")))
        default_dest = str(Path.home() / "Downloads" / "Steam Library")
        self.destination_var = tk.StringVar(value=str(self.config_data.get("destination", default_dest)))

        self._field(form, "Platform depots", ttk.Combobox(form, textvariable=self.os_var, values=("linux", "windows", "macos"), state="readonly"), 0)
        self._field(form, "Architecture", ttk.Combobox(form, textvariable=self.arch_var, values=("64", "32"), state="readonly"), 1)
        self._field(form, "Language", ttk.Entry(form, textvariable=self.language_var), 2)
        self._field(form, "Branch", ttk.Entry(form, textvariable=self.branch_var), 3)

        ttk.Label(form, text="Destination", style="PanelMuted.TLabel").grid(row=4, column=0, sticky="w", pady=(10, 4))
        destination = ttk.Frame(form, style="Panel.TFrame")
        destination.grid(row=5, column=0, sticky="ew")
        ttk.Entry(destination, textvariable=self.destination_var).pack(side="left", fill="x", expand=True)
        ttk.Button(destination, text="Browse", command=self.choose_destination).pack(side="left", padx=(7, 0))
        form.columnconfigure(0, weight=1)

        actions = ttk.Frame(right, style="Panel.TFrame")
        actions.pack(fill="x", pady=(16, 10))
        self.download_button = ttk.Button(actions, text="Download selected", style="Accent.TButton", command=self.download_selected)
        self.download_button.pack(side="left")
        self.cancel_button = ttk.Button(actions, text="Cancel", style="Danger.TButton", command=self.cancel_operation)
        self.cancel_button.pack(side="left", padx=(8, 0))
        ttk.Button(actions, text="Open folder", command=self.open_destination).pack(side="right")

        self.progress = ttk.Progressbar(right, orient="horizontal", mode="determinate", maximum=100)
        self.progress.pack(fill="x", pady=(2, 10))
        self.status_label = ttk.Label(right, text="Ready", style="PanelMuted.TLabel")
        self.status_label.pack(fill="x", pady=(0, 8))

        self.qr_card = ttk.Frame(right, style="Card.TFrame", padding=12)
        self.qr_canvas = tk.Canvas(self.qr_card, width=300, height=300, bg="#ffffff", highlightthickness=0)
        self.qr_canvas.pack()
        ttk.Label(self.qr_card, text="Scan in Steam Mobile, then approve the sign-in", style="Card.TLabel", anchor="center").pack(fill="x", pady=(8, 0))

        log_frame = ttk.Frame(right, style="Panel.TFrame")
        log_frame.pack(fill="both", expand=True, pady=(8, 0))
        self.log = tk.Text(log_frame, bg="#08080a", fg="#d7d2e3", insertbackground=TEXT, relief="flat", wrap="word", font=("Monospace", 9), padx=10, pady=10, height=10)
        log_scroll = ttk.Scrollbar(log_frame, orient="vertical", command=self.log.yview)
        self.log.configure(yscrollcommand=log_scroll.set)
        self.log.pack(side="left", fill="both", expand=True)
        log_scroll.pack(side="right", fill="y")

    def _field(self, parent: ttk.Frame, label: str, widget: ttk.Widget, index: int) -> None:
        row = index * 2
        ttk.Label(parent, text=label, style="PanelMuted.TLabel").grid(row=row, column=0, sticky="w", pady=(8 if index else 0, 4))
        widget.grid(row=row + 1, column=0, sticky="ew")
